name: service

on:
  push:
    branches:
      - master
      - stable
  pull_request:
    branches:
      - master
      - stable

jobs:
  service_test:
    name: Service plugin (Go ${{ matrix.go }}, PHP ${{ matrix.php }}, OS ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        php: [ "8.3" ]
        go: [ stable ]
        os: [ "ubuntu-latest" ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: ${{ matrix.go }}

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2 # action page: <https://github.com/shivammathur/setup-php>
        with:
          php-version: ${{ matrix.php }}
          extensions: sockets

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cd tests/php_test_files
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Init Composer Cache # Docs: <https://git.io/JfAKn#php---composer>
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: cd tests/php_test_files && composer update --prefer-dist --no-progress --ansi

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Increase FD limit
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          ulimit -n 5000

      - name: Install Go dependencies
        run: go mod download

      - name: Run service unit tests with coverage
        run: |
          mkdir ./tests/coverage-ci
          go test -timeout 20m -v -race -cover -tags=debug -failfast -coverpkg=$(cat ./tests/pkgs.txt) -coverprofile=./tests/coverage-ci/service_u.out -covermode=atomic config.go plugin.go process.go process_test.go rpc.go state.go

      - name: Run service e2e tests with coverage
        run: |
          cd tests
          
          chmod 777 php_test_files/test_binary
          chmod +x php_test_files/test_binary
          
          go test -timeout 20m -v -race -cover -tags=debug -failfast -coverpkg=$(cat pkgs.txt) -coverprofile=./coverage-ci/service.out -covermode=atomic service_plugin_test.go

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./tests/coverage-ci/

  codecov:
    name: Upload codecov
    runs-on: ubuntu-latest
    needs:
      - service_test

    timeout-minutes: 60
    steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v4
      - run: |
          cd coverage
          echo 'mode: atomic' > summary.txt
          tail -q -n +2 *.out >> summary.txt
          sed -i '2,${/roadrunner/!d}' summary.txt

      - name: upload to codecov
        uses: codecov/codecov-action@v3 # Docs: <https://github.com/codecov/codecov-action>
        with:
          file: ./coverage/summary.txt
          fail_ci_if_error: false
